--- #YAML:1.0
name:               Tree-Range
version:            0.1
abstract:           Map values belonging to non-overlapping ranges using a tree
author:
    - Ivan Shmakov <oneingray@gmail.com>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:      1.26
    perl:      5.01
    Tree::RB:  0.500003
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
